#release configuration
#Mon Oct 05 15:07:15 CDT 2026
completedPhase=end-release
exec.activateProfiles=deploy-to-scijava
exec.additionalArguments=-Dgpg.skip\=true 
exec.pomFileName=pom.xml
exec.snapshotReleasePluginAllowed=false
pinExternals=false
preparationGoals=clean verify
project.dev.sc.fiji\:fiji-llm=0.1.1-SNAPSHOT
project.rel.sc.fiji\:fiji-llm=0.1.0
project.scm.sc.fiji\:fiji-llm.connection=scm\:git\:https\://github.com/fiji/fiji-llm
project.scm.sc.fiji\:fiji-llm.developerConnection=scm\:git\:git@github.com\:fiji/fiji-llm
project.scm.sc.fiji\:fiji-llm.tag=HEAD
project.scm.sc.fiji\:fiji-llm.url=https\://github.com/fiji/fiji-llm
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
projectVersionPolicyId=default
pushChanges=false
releaseStrategyId=default
remoteTagging=true
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
scm.commentPrefix=[maven-release-plugin] 
scm.developmentCommitComment=@{prefix} prepare for next development iteration
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
scm.tag=fiji-llm-0.1.0
scm.tagNameFormat=@{project.artifactId}-@{project.version}
scm.url=scm\:git\:https\://github.com/fiji/fiji-llm
